// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import type { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCSgbUSGVzrB82ub1cSQwJdbCpCRekS-SA",
  authDomain: "lovechat-c483c.firebaseapp.com",
  databaseURL: "https://lovechat-c483c-default-rtdb.firebaseio.com",
  projectId: "lovechat-c483c",
  storageBucket: "lovechat-c483c.appspot.com",
  messagingSenderId: "648583863356",
  appId: "1:648583863356:web:a04d30ddb237da835c3739",
  measurementId: "G-Y7TZ7W6QNB"
};

    